name: Stale monitor

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    name: Stale
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: Automattic/vip-actions/stale@trunk
        with:
          days-before-stale: "30"
